name: CI

on: [push]

jobs:
  test:
    strategy:
      matrix:
        database: [ mysql, postgresql ]
        ruby: [ 2.7, 2.6 ]
      fail-fast: false
      max-parallel: 10
    runs-on: ubuntu-latest

    env:
      CI: true
      DB: ${{ matrix.database }}
      MYSQL_PASSWORD: root
      PGHOST: localhost
      PGUSER: postgres
      PGPASSWORD: postgres
      RAILS_ENV: test

    name: ${{ matrix.ruby }} ${{ matrix.database }}
    steps:
      - run: sudo apt-get update && sudo apt-get install libpq-dev libmysqlclient-dev libsqlite3-dev -y
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}
      - run: sudo systemctl start mysql.service
      - run: bin/rake refinery:testing:dummy_app
        env:
          PGPORT: ${{ job.services.postgres.ports[5432] }}

      - run: bin/rspec spec
        env:
          PGPORT: ${{ job.services.postgres.ports[5432] }}
          RETRY_COUNT: 3

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
